[package]
name = "omnicounter"
version = "0.0.1"

[addresses]
test = "0x8"
lzapp = "0x9"

[dependencies]
layerzero = { local = "./layerzero" }
layerzero_common = { local = "./layerzero-common" }
executor_auth = { local = "./executor/executor-auth" }
msglib_auth = { local = "./msglib/msglib-auth" }
msglib_v1_1 = { local = "./msglib/msglib-v1/msglib-v1-1" }
zro = { local = "./zro" }
msglib_v2 = { local = "./msglib/msglib-v2" }
executor_v2 = { local = "./executor/executor-v2" }