[package]
name = "msglib_v1_1"
version = "0.0.1"

[addresses]
msglib_v1_1 = "_"

[dependencies]
layerzero_common = { local = "../../../layerzero-common" }
msglib_auth = { local = "../../msglib-auth" }
zro = { local = "../../../zro" }